version: 0.2 
phases: 
  install:
    runtime-versions:
      nodejs: 10
  pre_build: 
    commands: 
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)" 
  build: 
    commands: 
      - npm install 
      - npm run ${BUILD_TYPE} 
  post_build: 
    commands: 
      - aws s3 rm s3://$TARGET_BUCKET --recursive 
      - aws s3 sync build s3://$TARGET_BUCKET 
      - printf '{"tag":"%s","target-bucket":"%s", "build-type":"%s"}' $TAG $TARGET_BUCKET $BUILD_TYPE > build.json 
artifacts: 
  files:  
    - build.json 